### ISSUE TITLE
add option in outputs configuration to filter queries

### ISSUE THREAD

**Issue by caskolkm** [shamil/graphout#1]

**Comment by shamil** [comment]
In the latest version ([0.3.0](https://www.npmjs.com/package/graphout)) you have a `filter` option, which can be used to process only matched queries. Let me know if that what you asked for...

**P.S.**
Another change in the new version is that the `calculation` option is now configured per `output` and not globally per `query`.

**Comment by caskolkm** [comment]
Cool, thnx. maybe i can write a puppet module for you!

**Comment by shamil** [comment]
Sure, that will be great :)
